### ISSUE TITLE
No INPUT matching '#username-login-username'

### ISSUE THREAD

**Issue by dlbrown06** [martzmakes/node-fitocracy#1]
Appears this library is no longer being maintained.

Either figured I would report that the auth doesn't appear to be working anymore:

```
 AssertionError: No INPUT matching '#username-login-username'
    at Browser.fill (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\lib\zombie\browser.js:622:5)
    at C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\index.js:27:18
    at tryCatcher (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\dbrown\Developer\personal\fitocracy-proper\node_modules\node-fitocracy\node_modules\zombie\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Would love to expand on this module to auto prop your friends that you follow.

**Comment by martzmakes** [comment]
Yeah, I ended up not using this for any of my personal projects.  It's been a year or two since I made it so I'm sure fitocracy changed the layout of their site which broke it.

PRs are welcome if you need it and figure out the fix!

**Comment by dlbrown06** [comment]
Well I was planning on putting in a PR. I updated the form username and password fill inputs. After pressButton on 'Log In', it looks like it doesn't redirect to the homepage, so something else must still be going on.
